#!/bin/bash

projectdir=$1
github_uname=$2

USAGE="${0} <absolute-path-to-project> <github_username>"

if [[ ${projectdir} = "" && ${github_uname} = "" ]]; then
    echo "Please provide valid path to the project and github username."
    echo ${USAGE}
    exit 1
fi


if [[ "${projectdir}" != /* ]]; then
    echo "Please provide absolute path to where you want to create the pypi bootstrap directory"
    echo "Eg. if you want to create 'demo-package' in '/home/joe/projects', then pass '/home/joe/projects/demo-package'"
    echo ${USAGE}
    exit 2
fi

if [ -d ${projectdir} ]; then
    echo
    echo "Project '${projectdir}' already exists!"
    echo
    read -r -p "Do you want to override? (This will FORCE remove ALL content and OEVERWRITE everything with the scaffold files.) [y/N]: " response
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
        rm -rf ${projectdir}/
        echo
        echo "Overwriting project files with fresh scaffold files: ${projectdir}"
    else
        echo "Exiting"
        exit 0
    fi
fi
gitignore=${projectdir}/.gitignore
projectname=`basename ${projectdir}`
echo
echo
echo "Creating python PYPI style package '${projectname}' in '`realpath ${projectdir}`'..."
mkdir ${projectdir}

echo "Copying seed files..."
cp -r pypi-project/* ${projectdir}/
mv ${projectdir}/pypi-package ${projectdir}/${projectname}

cd ${projectdir}
entrypoint=${projectname}-entry

# get Python based .gitignore
wget https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore -O $gitignore  > /dev/null 2>&1

echo "Updating project metadata (name, entrypoint references, etc.)..."
# update package name references
find . -not -path './.git/*' -type f -exec sed -i "s/YOUR_PROJECT_NAME/${projectname}/g" {} \;

# update entrypoint reference
find . -not -path './.git/*' -type f -exec sed -i "s/YOUR_PROJECT_ENTRYPOINT/${entrypoint}/g" {} \;

# setup github repo locally and reference the remote
echo
echo "[Git] Initializing..."
git init -q
echo "[Git] Staging generated files to the repository and adding initial commit..."
git add -A
git add $gitignore
git commit -q -m "Add initial setup for pypi style project"
echo "[Git] Updating remote origin..."
git remote add origin git@github.com:${github_uname}/${projectname}.git

echo
listfiles="ls -latr ${projectdir}"
echo List of Generated Files:
echo \$ ${listfiles}
${listfiles}

echo
echo
echo "Next, complete the following steps:"
echo "1. Navigte to '${projectdir}'."
echo "2. Verify file changes and references using 'git diff' and 'git status' commands."
echo "3. Read README.md and Makefile for important targets."
echo
echo "PYPI package name: '${projectname}'"
echo "PYPI entrypoint script for verifying installation (exported to '/usr/local/bin' after installation): '${entrypoint}'"
echo "PYPI style package file structure creation completed."
echo
